### ISSUE TITLE
VIRUS 

### ISSUE THREAD

**Issue by ElryGH** [tall1on/ExaGameBooster#8]
Installer.exe - 41 Detections, this amount cannot all be false positives !!!!
https://www.virustotal.com/gui/file/75148355606aee0cfe6facc9b97f064748c2ba5cc268f275c51e7a83edcfb881
![image](https://github.com/user-attachments/assets/da5ab129-052a-4d26-a8e2-d7a14cdfdc37)
ExaGameBooster.exe - 31 Detection, again this amount cannot be a false positive !
https://www.virustotal.com/gui/file/de51ba4b9701e5cd57b2f82b5394f4a515dbab90f552a4ab2854e9376f00ef21
Again windows also comes up with a Malicous file warning !
![image](https://github.com/user-attachments/assets/82c147c9-514c-4ab4-8aa9-6bc935ba093d)

**Comment by tall1on** [comment]
Unfortunately, they are. Instead of spreading false information without knowledge, I would recommend that you take a look at the open source code and compile it yourself. You will get exactly the same detections. 

It seems to be a mix, because currently the list of .exe applications that need to get handles is included in the code instead of being loaded from a config. Also the solution to check for updates seems to cause problems with the detection. The installer is then the last part, as registry keys are logically set. Since I do not have a code signing certificate either, the program is detected as a virus by the certificate cartel.

The best indicator that it is not malware is that Kaspersky does not detect anything. Kaspersky is without question the best antivirus program and does not rely on any fantasies and detects real malware.
